# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InternalTypes.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='InternalTypes.proto',
  package='',
  serialized_pb='\n\x13InternalTypes.proto\"*\n\x0c\x41vgLongProto\x12\x0b\n\x03sum\x18\x01 \x02(\x03\x12\r\n\x05\x63ount\x18\x02 \x02(\x03\",\n\x0e\x41vgDoubleProto\x12\x0b\n\x03sum\x18\x01 \x02(\x01\x12\r\n\x05\x63ount\x18\x02 \x02(\x03\x42&\n\x0forg.apache.tajoB\rInternalTypes\x88\x01\x00\xa0\x01\x01')




_AVGLONGPROTO = _descriptor.Descriptor(
  name='AvgLongProto',
  full_name='AvgLongProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sum', full_name='AvgLongProto.sum', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='AvgLongProto.count', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=65,
)


_AVGDOUBLEPROTO = _descriptor.Descriptor(
  name='AvgDoubleProto',
  full_name='AvgDoubleProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sum', full_name='AvgDoubleProto.sum', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='AvgDoubleProto.count', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=67,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['AvgLongProto'] = _AVGLONGPROTO
DESCRIPTOR.message_types_by_name['AvgDoubleProto'] = _AVGDOUBLEPROTO

class AvgLongProto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AVGLONGPROTO

  # @@protoc_insertion_point(class_scope:AvgLongProto)

class AvgDoubleProto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AVGDOUBLEPROTO

  # @@protoc_insertion_point(class_scope:AvgDoubleProto)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\017org.apache.tajoB\rInternalTypes\210\001\000\240\001\001')
# @@protoc_insertion_point(module_scope)
