# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QueryMasterClientProtocol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import tajo_protos_pb2
import TajoIdProtos_pb2
import CatalogProtos_pb2
import PrimitiveProtos_pb2
import ClientProtos_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='QueryMasterClientProtocol.proto',
  package='',
  serialized_pb='\n\x1fQueryMasterClientProtocol.proto\x1a\x11tajo_protos.proto\x1a\x12TajoIdProtos.proto\x1a\x13\x43\x61talogProtos.proto\x1a\x15PrimitiveProtos.proto\x1a\x12\x43lientProtos.proto2`\n QueryMasterClientProtocolService\x12<\n\x0fgetQueryHistory\x12\x0f.QueryIdRequest\x1a\x18.GetQueryHistoryResponseB6\n\x13org.apache.tajo.ipcB\x19QueryMasterClientProtocol\x88\x01\x01\xa0\x01\x01')





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\023org.apache.tajo.ipcB\031QueryMasterClientProtocol\210\001\001\240\001\001')
# @@protoc_insertion_point(module_scope)
