# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TestProtos.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TestProtos.proto',
  package='',
  serialized_pb='\n\x10TestProtos.proto\";\n\x10TestMessageProto\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0b\n\x03\x61ge\x18\x02 \x02(\x05\x12\x0c\n\x04\x61\x64\x64r\x18\x03 \x02(\tB(\n\x14org.apache.tajo.utilB\nTestProtos\x88\x01\x01\xa0\x01\x01')




_TESTMESSAGEPROTO = _descriptor.Descriptor(
  name='TestMessageProto',
  full_name='TestMessageProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='TestMessageProto.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='age', full_name='TestMessageProto.age', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='addr', full_name='TestMessageProto.addr', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['TestMessageProto'] = _TESTMESSAGEPROTO

class TestMessageProto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTMESSAGEPROTO

  # @@protoc_insertion_point(class_scope:TestMessageProto)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\024org.apache.tajo.utilB\nTestProtos\210\001\001\240\001\001')
# @@protoc_insertion_point(module_scope)
