# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TajoIdProtos.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TajoIdProtos.proto',
  package='',
  serialized_pb='\n\x12TajoIdProtos.proto\"\'\n\x0cQueryIdProto\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0b\n\x03seq\x18\x02 \x02(\x05\"C\n\x15\x45xecutionBlockIdProto\x12\x1e\n\x07queryId\x18\x01 \x02(\x0b\x32\r.QueryIdProto\x12\n\n\x02id\x18\x02 \x02(\x05\"K\n\x0bTaskIdProto\x12\x30\n\x10\x65xecutionBlockId\x18\x01 \x02(\x0b\x32\x16.ExecutionBlockIdProto\x12\n\n\x02id\x18\x02 \x02(\x05\">\n\x12TaskAttemptIdProto\x12\x1c\n\x06taskId\x18\x01 \x02(\x0b\x32\x0c.TaskIdProto\x12\n\n\x02id\x18\x02 \x02(\x05\"\x1c\n\x0eSessionIdProto\x12\n\n\x02id\x18\x01 \x02(\tB%\n\x0forg.apache.tajoB\x0cTajoIdProtos\x88\x01\x00\xa0\x01\x01')




_QUERYIDPROTO = _descriptor.Descriptor(
  name='QueryIdProto',
  full_name='QueryIdProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='QueryIdProto.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='QueryIdProto.seq', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=61,
)


_EXECUTIONBLOCKIDPROTO = _descriptor.Descriptor(
  name='ExecutionBlockIdProto',
  full_name='ExecutionBlockIdProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queryId', full_name='ExecutionBlockIdProto.queryId', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='ExecutionBlockIdProto.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=63,
  serialized_end=130,
)


_TASKIDPROTO = _descriptor.Descriptor(
  name='TaskIdProto',
  full_name='TaskIdProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='executionBlockId', full_name='TaskIdProto.executionBlockId', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='TaskIdProto.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=132,
  serialized_end=207,
)


_TASKATTEMPTIDPROTO = _descriptor.Descriptor(
  name='TaskAttemptIdProto',
  full_name='TaskAttemptIdProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='TaskAttemptIdProto.taskId', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='TaskAttemptIdProto.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=209,
  serialized_end=271,
)


_SESSIONIDPROTO = _descriptor.Descriptor(
  name='SessionIdProto',
  full_name='SessionIdProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SessionIdProto.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=273,
  serialized_end=301,
)

_EXECUTIONBLOCKIDPROTO.fields_by_name['queryId'].message_type = _QUERYIDPROTO
_TASKIDPROTO.fields_by_name['executionBlockId'].message_type = _EXECUTIONBLOCKIDPROTO
_TASKATTEMPTIDPROTO.fields_by_name['taskId'].message_type = _TASKIDPROTO
DESCRIPTOR.message_types_by_name['QueryIdProto'] = _QUERYIDPROTO
DESCRIPTOR.message_types_by_name['ExecutionBlockIdProto'] = _EXECUTIONBLOCKIDPROTO
DESCRIPTOR.message_types_by_name['TaskIdProto'] = _TASKIDPROTO
DESCRIPTOR.message_types_by_name['TaskAttemptIdProto'] = _TASKATTEMPTIDPROTO
DESCRIPTOR.message_types_by_name['SessionIdProto'] = _SESSIONIDPROTO

class QueryIdProto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYIDPROTO

  # @@protoc_insertion_point(class_scope:QueryIdProto)

class ExecutionBlockIdProto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXECUTIONBLOCKIDPROTO

  # @@protoc_insertion_point(class_scope:ExecutionBlockIdProto)

class TaskIdProto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASKIDPROTO

  # @@protoc_insertion_point(class_scope:TaskIdProto)

class TaskAttemptIdProto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASKATTEMPTIDPROTO

  # @@protoc_insertion_point(class_scope:TaskAttemptIdProto)

class SessionIdProto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SESSIONIDPROTO

  # @@protoc_insertion_point(class_scope:SessionIdProto)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\017org.apache.tajoB\014TajoIdProtos\210\001\000\240\001\001')
# @@protoc_insertion_point(module_scope)
