# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContainerProtocol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import Security_pb2
import yarn_protos_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ContainerProtocol.proto',
  package='hadoop.yarn',
  serialized_pb='\n\x17\x43ontainerProtocol.proto\x12\x0bhadoop.yarn\x1a\x0eSecurity.proto\x1a\x11yarn_protos.proto\"\x93\x01\n\x14TajoContainerIdProto\x12/\n\x06\x61pp_id\x18\x01 \x01(\x0b\x32\x1f.hadoop.yarn.ApplicationIdProto\x12>\n\x0e\x61pp_attempt_id\x18\x02 \x01(\x0b\x32&.hadoop.yarn.ApplicationAttemptIdProto\x12\n\n\x02id\x18\x03 \x01(\x05\"\x98\x02\n\x12TajoContainerProto\x12-\n\x02id\x18\x01 \x01(\x0b\x32!.hadoop.yarn.TajoContainerIdProto\x12(\n\x06nodeId\x18\x02 \x01(\x0b\x32\x18.hadoop.yarn.NodeIdProto\x12\x19\n\x11node_http_address\x18\x03 \x01(\t\x12,\n\x08resource\x18\x04 \x01(\x0b\x32\x1a.hadoop.yarn.ResourceProto\x12,\n\x08priority\x18\x05 \x01(\x0b\x32\x1a.hadoop.yarn.PriorityProto\x12\x32\n\x0f\x63ontainer_token\x18\x06 \x01(\x0b\x32\x19.hadoop.common.TokenProtoB.\n\x13org.apache.tajo.ipcB\x11\x43ontainerProtocol\x88\x01\x01\xa0\x01\x01')




_TAJOCONTAINERIDPROTO = _descriptor.Descriptor(
  name='TajoContainerIdProto',
  full_name='hadoop.yarn.TajoContainerIdProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_id', full_name='hadoop.yarn.TajoContainerIdProto.app_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app_attempt_id', full_name='hadoop.yarn.TajoContainerIdProto.app_attempt_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='hadoop.yarn.TajoContainerIdProto.id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=76,
  serialized_end=223,
)


_TAJOCONTAINERPROTO = _descriptor.Descriptor(
  name='TajoContainerProto',
  full_name='hadoop.yarn.TajoContainerProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hadoop.yarn.TajoContainerProto.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nodeId', full_name='hadoop.yarn.TajoContainerProto.nodeId', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_http_address', full_name='hadoop.yarn.TajoContainerProto.node_http_address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resource', full_name='hadoop.yarn.TajoContainerProto.resource', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='priority', full_name='hadoop.yarn.TajoContainerProto.priority', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='container_token', full_name='hadoop.yarn.TajoContainerProto.container_token', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=226,
  serialized_end=506,
)

_TAJOCONTAINERIDPROTO.fields_by_name['app_id'].message_type = yarn_protos_pb2._APPLICATIONIDPROTO
_TAJOCONTAINERIDPROTO.fields_by_name['app_attempt_id'].message_type = yarn_protos_pb2._APPLICATIONATTEMPTIDPROTO
_TAJOCONTAINERPROTO.fields_by_name['id'].message_type = _TAJOCONTAINERIDPROTO
_TAJOCONTAINERPROTO.fields_by_name['nodeId'].message_type = yarn_protos_pb2._NODEIDPROTO
_TAJOCONTAINERPROTO.fields_by_name['resource'].message_type = yarn_protos_pb2._RESOURCEPROTO
_TAJOCONTAINERPROTO.fields_by_name['priority'].message_type = yarn_protos_pb2._PRIORITYPROTO
_TAJOCONTAINERPROTO.fields_by_name['container_token'].message_type = Security_pb2._TOKENPROTO
DESCRIPTOR.message_types_by_name['TajoContainerIdProto'] = _TAJOCONTAINERIDPROTO
DESCRIPTOR.message_types_by_name['TajoContainerProto'] = _TAJOCONTAINERPROTO

class TajoContainerIdProto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TAJOCONTAINERIDPROTO

  # @@protoc_insertion_point(class_scope:hadoop.yarn.TajoContainerIdProto)

class TajoContainerProto(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TAJOCONTAINERPROTO

  # @@protoc_insertion_point(class_scope:hadoop.yarn.TajoContainerProto)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\023org.apache.tajo.ipcB\021ContainerProtocol\210\001\001\240\001\001')
# @@protoc_insertion_point(module_scope)
