# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QueryMasterProtocol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import yarn_protos_pb2
import tajo_protos_pb2
import TajoIdProtos_pb2
import CatalogProtos_pb2
import PrimitiveProtos_pb2
import TajoWorkerProtocol_pb2
import ContainerProtocol_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='QueryMasterProtocol.proto',
  package='hadoop.yarn',
  serialized_pb='\n\x19QueryMasterProtocol.proto\x12\x0bhadoop.yarn\x1a\x11yarn_protos.proto\x1a\x11tajo_protos.proto\x1a\x12TajoIdProtos.proto\x1a\x13\x43\x61talogProtos.proto\x1a\x15PrimitiveProtos.proto\x1a\x18TajoWorkerProtocol.proto\x1a\x17\x43ontainerProtocol.proto2\xf4\x03\n\x1aQueryMasterProtocolService\x12J\n\x07getTask\x12 .hadoop.yarn.GetTaskRequestProto\x1a\x1d.hadoop.yarn.TaskRequestProto\x12\x38\n\x0cstatusUpdate\x12\x1c.hadoop.yarn.TaskStatusProto\x1a\n.BoolProto\x12*\n\x04ping\x12\x16.ExecutionBlockIdProto\x1a\n.BoolProto\x12;\n\nfatalError\x12!.hadoop.yarn.TaskFatalErrorReport\x1a\n.BoolProto\x12\x35\n\x04\x64one\x12!.hadoop.yarn.TaskCompletionReport\x1a\n.BoolProto\x12\x43\n\x12\x64oneExecutionBlock\x12!.hadoop.yarn.ExecutionBlockReport\x1a\n.BoolProto\x12&\n\tkillQuery\x12\r.QueryIdProto\x1a\n.BoolProto\x12\x43\n\x0c\x65xecuteQuery\x12\'.hadoop.yarn.QueryExecutionRequestProto\x1a\n.BoolProtoB0\n\x13org.apache.tajo.ipcB\x13QueryMasterProtocol\x88\x01\x01\xa0\x01\x01')





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\023org.apache.tajo.ipcB\023QueryMasterProtocol\210\001\001\240\001\001')
# @@protoc_insertion_point(module_scope)
