# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResourceTrackerProtocol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import QueryCoordinatorProtocol_pb2
import ContainerProtocol_pb2
import tajo_protos_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ResourceTrackerProtocol.proto',
  package='hadoop.yarn',
  serialized_pb='\n\x1dResourceTrackerProtocol.proto\x12\x0bhadoop.yarn\x1a\x1eQueryCoordinatorProtocol.proto\x1a\x17\x43ontainerProtocol.proto\x1a\x11tajo_protos.proto\"\x90\x01\n\rNodeHeartbeat\x12\x32\n\x0e\x63onnectionInfo\x18\x01 \x02(\x0b\x32\x1a.WorkerConnectionInfoProto\x12\x34\n\x0cserverStatus\x18\x02 \x01(\x0b\x32\x1e.hadoop.yarn.ServerStatusProto\x12\x15\n\rstatusMessage\x18\x03 \x01(\t2q\n\"TajoResourceTrackerProtocolService\x12K\n\theartbeat\x12\x1a.hadoop.yarn.NodeHeartbeat\x1a\".hadoop.yarn.TajoHeartbeatResponseB8\n\x13org.apache.tajo.ipcB\x1bTajoResourceTrackerProtocol\x88\x01\x01\xa0\x01\x01')




_NODEHEARTBEAT = _descriptor.Descriptor(
  name='NodeHeartbeat',
  full_name='hadoop.yarn.NodeHeartbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='connectionInfo', full_name='hadoop.yarn.NodeHeartbeat.connectionInfo', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serverStatus', full_name='hadoop.yarn.NodeHeartbeat.serverStatus', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='statusMessage', full_name='hadoop.yarn.NodeHeartbeat.statusMessage', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=123,
  serialized_end=267,
)

_NODEHEARTBEAT.fields_by_name['connectionInfo'].message_type = tajo_protos_pb2._WORKERCONNECTIONINFOPROTO
_NODEHEARTBEAT.fields_by_name['serverStatus'].message_type = QueryCoordinatorProtocol_pb2._SERVERSTATUSPROTO
DESCRIPTOR.message_types_by_name['NodeHeartbeat'] = _NODEHEARTBEAT

class NodeHeartbeat(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NODEHEARTBEAT

  # @@protoc_insertion_point(class_scope:hadoop.yarn.NodeHeartbeat)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\023org.apache.tajo.ipcB\033TajoResourceTrackerProtocol\210\001\001\240\001\001')
# @@protoc_insertion_point(module_scope)
