# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RpcProtos.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RpcProtos.proto',
  package='',
  serialized_pb='\n\x0fRpcProtos.proto\"F\n\nRpcRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x13\n\x0bmethod_name\x18\x02 \x02(\t\x12\x17\n\x0frequest_message\x18\x03 \x01(\x0c\"t\n\x0bRpcResponse\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x18\n\x10response_message\x18\x02 \x01(\x0c\x12\x13\n\x0b\x65rror_class\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12\x13\n\x0b\x65rror_trace\x18\x05 \x01(\tB \n\x13org.apache.tajo.rpcB\tRpcProtos')




_RPCREQUEST = _descriptor.Descriptor(
  name='RpcRequest',
  full_name='RpcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RpcRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='method_name', full_name='RpcRequest.method_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_message', full_name='RpcRequest.request_message', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=19,
  serialized_end=89,
)


_RPCRESPONSE = _descriptor.Descriptor(
  name='RpcResponse',
  full_name='RpcResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RpcResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response_message', full_name='RpcResponse.response_message', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_class', full_name='RpcResponse.error_class', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='RpcResponse.error_message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_trace', full_name='RpcResponse.error_trace', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=91,
  serialized_end=207,
)

DESCRIPTOR.message_types_by_name['RpcRequest'] = _RPCREQUEST
DESCRIPTOR.message_types_by_name['RpcResponse'] = _RPCRESPONSE

class RpcRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RPCREQUEST

  # @@protoc_insertion_point(class_scope:RpcRequest)

class RpcResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RPCRESPONSE

  # @@protoc_insertion_point(class_scope:RpcResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\023org.apache.tajo.rpcB\tRpcProtos')
# @@protoc_insertion_point(module_scope)
